[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.2.2
    adafruit/Adafruit Unified Sensor @ ^1.1.13
    Wire

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -DNODE_ID=1
    ; Change NODE_ID (1-4) per device before flashing
